HTTP/1.1 200 OK
Host: example.org
Accept-Query: example/events-query
Content-Type: example/event-notification
Incremental: ?1

published: 2025-01-02T10:11:12.345Z              | Notification
event-ID: 456                                    |
type: Update                                     |
