HTTP/1.1 200 OK                                  | Notification
Content-Type: example/event-notification         |
Content-Length: 31                               |
                                                 |
Event-ID: 789                                    |
Type: Delete                                     |
