HTTP/1.1 200 OK                                  | Notification
Content-Type: example/event-notification         |
Content-Length: 31                               |
                                                 |
published: 2012-11-10T12:13:14.567Z              |
event-id: 789                                    |
type: delete                                     |
